spring.application.name=csv-processor

# Allow large CSV file uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Server port
server.port=8080

# Logging
logging.level.com.ga.csvprocessor=DEBUG